### ISSUE TITLE
virtualenv: contains neither jython-dev.jar nor jython.jar

### ISSUE THREAD

**Issue by baztian** [jython/frozen-mirror#160]
I'm not able to create a virtualenv with jython. I'm getting the following error. I've downloaded via maven central.

    me@mybox:/opt/jython-2.7.2b2/bin$ ./virtualenv /tmp/foo
    New python executable in /tmp/foo/bin/jython
    Also creating executable in /tmp/foo/bin/python
    /tmp/foo/bin/jython:  contains neither jython-dev.jar nor jython.jar.
    Try running this script from the 'bin' directory of an installed Jython or 
    setting $JYTHON_HOME.
    ERROR: The executable /tmp/foo/bin/jython is not functioning
    ERROR: It thinks sys.prefix is '/opt/jython-2.7.2b2/bin' (should be u'/tmp/foo')
    ERROR: virtualenv is not compatible with this system or executable

    me@mybox:/opt/jython-2.7.2b2$ ls -l
    total 32520
    -rw-r--r--  1 root root     5134 Nov  1 05:37 ACKNOWLEDGMENTS
    drwxr-xr-x  2 root root     4096 Nov 10 21:00 bin
    drwxr-xr-x  3 root root     4096 Nov 10 20:59 cachedir
    -rw-r--r--  1 root root     8650 Nov  1 05:37 CoreExposed.includes
    drwxr-xr-x 10 root root     4096 Nov 10 20:59 Demo
    drwxr-xr-x  3 root root     4096 Nov 10 20:59 Doc
    drwxr-xr-x  2 root root     4096 Nov 10 20:59 javalib
    -rw-r--r--  1 root root 33042674 Nov  1 07:48 jython.jar
    drwxr-xr-x 20 root root    20480 Nov 10 20:59 Lib
    -rw-r--r--  1 root root    11358 Nov  1 05:37 LICENSE_Apache.txt
    -rw-r--r--  1 root root    38592 Nov  1 05:37 LICENSE_CPython.txt
    -rw-r--r--  1 root root     9936 Nov  1 05:37 LICENSE.txt
    -rw-r--r--  1 root root   108151 Nov  1 05:37 NEWS
    -rw-r--r--  1 root root     1613 Nov  1 07:49 README.txt
    -rw-r--r--  1 root root     5845 Nov  1 05:37 registry
    drwxr-xr-x  3 root root     4096 Nov 10 20:59 tests

**Comment by jeff5** [comment]
I'm sure I've had `virtualenv` work for me in the past ... but I confirm the observed behaviour. This does not seem to depend on using `/tmp`: I had it fail for local directory `venv`.

The problem is that the Jython launcher is copied (not linked) into the virtual installation `bin` directory, and looks for the JAR adjacent to itself. `virtualenv` is broken because it does not copy the JAR as well. And then it gives up before installing the activation script. On the face of it, I don't see how the script could possibly solve this problem on its own.

However, `virtualenv` does manage to run Jython, or it wouldn't be able to ask it for `sys.prefix`.

I wonder if we can do something in the wrapper or interpreter to exploit `Lib/orig-prefix.txt` in the virtual environment?

**Comment by baztian** [comment]
I can confirm that it worked in the past. I don't know which change made it fail.

**Comment by cclauss** [comment]
https://github.com/pypa/virtualenv/pull/1357
vitrualenv release 16.6.0 drop all references to Jython

virtualenv release 20.0.11 make that explicit
https://virtualenv.pypa.io/en/latest/changelog.html?highlight=jython#v20-0-11-2020-03-18

**Comment by jeff5** [comment]
Problem solved (sort of). :(
