### ISSUE TITLE
Compiling to Java .jar or .class and using JD_GUI

### ISSUE THREAD

**Issue by Logmytech** [jython/frozen-mirror#42]
How would I compile to standalone .jar ?

Can I generate a .class source?

Can I compile to .jar and use a Java decompiler like JD-GUI to get Java Source?

**Comment by Stewori** [comment]
What do you want to compile? Jython? Or your app?
You can compile Jython standalone via `ant jar-standalone`
To create a standalone of your app see http://www.jython.org/jythonbook/en/1.0/SimpleWebApps.html?highlight=explode#distributing-via-standalone-jar
also take a look at the recent thread on the mailing list (ImportError: No module named re).

To generate classes from .py files, just run Jython, it generates class-files on the fly. However, you can explicitly compile .py to .class using `import compileall; compileall.compile_dir('[your code-directory]')`.
See the JyNI-makefile for an example to run this with Jython from terminal as a one-liner and in context of a makefile: https://github.com/Stewori/JyNI/blob/master/makefile

You can use a Java-decompiler on Jython-generated class-files. However don't expect a much intuitive or readable result. The code doesn't use the Jython-API a human would use to access Python from Java. It directly calls stuff in `PyCode` etc AFAIK. What do you want to achieve with the decompilation? (maybe there's a better way)

**Comment by Logmytech** [comment]
I want to compile `.py` classes.

So I use 
```
import compileall;
compileall.compile_dir('[/home/user/my_py_scripts]')
```

**Comment by Stewori** [comment]
Unfortunately Jython cannot run on Android, because Android prohibits loading of new classes at runtime (i.e after initial startup).  Jython needs this for glue purposes. There's a concept to solve this using original Python bytcode, but  AFAIK nobody is working in it. I also hope that Jython will support Android, but don't have time to work on this front. Maybe when JyNI is feature-complete.

**Comment by Logmytech** [comment]
But I should be able to generate Java code for pure logic code that doesn't use any of the Python libraries and stick to Java Libraries, right?

I just want simple Python logic code converted to pure Java source code. I'll figure where to add that code to android myself.

```
def calc_numerology(num):
"""The logic for Numerology. Can this be converted to Java source code?"
    return(num/9)
```

**Comment by Stewori** [comment]
> But I should be able to generate Java code for pure logic code that doesn't use any of the Python libraries and stick to Java Libraries, right?

With Jython, this shouldn't matter; Python-libraries actually become "pure" Java-libraries in bytecode-sense. (Btw, your pure logic-code would be written in Python, wouldn't it?)
This is not a Python vs Java code issue, but a generating- and loading-classes-at-runtime-issue.
Sure you can try, but up to my knowledge this wouldn't work. I am also concerned that it is not even possible to precompile .py to .class - not using Python's dynamic features - and run this on Android. @jimbaker explained to me that even if you precompile everything, Jython still needs to generate something (glue-stuff) at runtime. I might be wrong given that I didn't actually test it myself, but AFAIK this applies no matter whether the used .class file was compiled from a .py or .java code-file.

**Comment by jamesmudd** [comment]
If you want to compile python in to class files there is another jython project attempting to make that work called clamp https://github.com/jythontools/clamp  it might be worth having a look at that. Its a very early stage project though...

**Comment by Stewori** [comment]
While it's a really beautiful idea, clamp will still generate Java code that depends on the Jython runtime library, so it wouldn't be workable on android in foreseeable future.

I have been thinking about what @Logmytech aked for, i.e if Python-code only uses Java-classes the resulting Java-code should also only depend on these classes and work on android etc. To emulate dynamic features of Python, the Jython runtime dependency with all its trickery is inevitable, but I think it might be doable for Pythoncode that actually does not make use of dynamical language features, i.e. only uses classes etc in conventional ways. While it may sound restrictive, I believe there is *a lot* Python code out there for which that applies.

BTW, there is a name for the Python subset not using dynamical features: [RPython](https://rpython.readthedocs.io).

I am thinking of a tight RPython to Java src-to-src compiler that creates plain Jython-independent Java code from RPython (still including hooks that allow Jython to utilize it well), but falls back to usual Jython mode otherwise. (This would also allow to port lots of stuff from PyPy directly to Java.) It can make use of PEP484-style type annotations to select suitable Java-types. As a preparation for utilizing type-annotations (among other goals) I am currently working on the [pytypes](https://github.com/Stewori/pytypes) project. Hope to release a beta version of pytypes soon.

**Comment by darjus** [comment]
@Stewori Regarding RPython to Java. I haven't looked at Pypy in a while, but I've seen something like that already there.

Regarding Clamp. I've been planning to add a feature where if only Java types are used, one could generate JVM bytecode that does not depend on Jython runtime. Such methods would have to be decorated/annotated in advance, and obviously no dynamic features involved. Imagine using Python 3.6 type syntax that generates JVM bytecodes. Should not be too much work for basic cases, but Jython is nowhere near 3.6 :D

**Comment by Stewori** [comment]
Clamp doesn't have to wait for Jython 3.5 or 3.6. There is this 2.7 style notation backport:
https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code

However, that type-information is not readily accessible via __annotations__ but that's an aspect pytypes can handle.
pytypes does not yet have PEP 526 support but that will come, much earlier than Jython 3.6 I suspect.
One goal of pytypes is to make PEP 484 and 526 typing stuff conveniently usable in Jython and Python 2.7.

Regarding PyPy: I think there was a Java backend for RPython once but it was abandoned a while ago.
